name: esp-lab
channels:
  - conda-forge
  - nodefaults
dependencies:
  - pytest-cov
  - pre-commit
  - bokeh
  - bottleneck
  - cartopy
  - click=8.0  # click newer than 8.0 breaks dask 2021.9 (see https://github.com/dask/distributed/issues/6013)
  - climpred
  - cf-units
  - cftime
  - cmocean
  - dask==2021.9
  - dask-jobqueue
  - distributed==2021.9
  - dask-labextension
  - eofs
  - esmpy
  - holoviews
  - intake
  - intake-esm
  - ipykernel
  - ipywidgets
  - jupyter-server-proxy
  - jupyterlab
  - matplotlib
  - metpy
  - nc-time-axis
  - netcdf4
  - nodejs
  - notebook
  - numba
  - numpy
  - pandas
  - pint
  - pip
  - pop-tools
  - pre-commit
  - pytest
  - pytest-cov
  - python==3.8
  - scipy
  - seaborn
  - seawater
  - statsmodels
  - toolz
  - tqdm
  - watermark
  - xarray>=0.19
  - xesmf # xarray interface it ESMF tools
  - xgcm # General Circulation Model Postprocessing with xarray
  - xhistogram # Fast, flexible, label-aware histograms for numpy and xarray
  - xrft # fourier transforms for xarray data
  - xskillscore>=0.0.23
  - zarr
  - ncar-jobqueue
